/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./components/404.vue')['default']
    '聊天机器人好看版': typeof import('./components/聊天机器人好看版.vue')['default']
    '聊天机器人需求样式版': typeof import('./components/聊天机器人需求样式版.vue')['default']
    '暂存': typeof import('./components/暂存.vue')['default']
    CesiumOfferice: typeof import('./components/CesiumOfferice.vue')['default']
    DynamicDeviceConfigForm: typeof import('./components/DynamicDeviceConfigForm.vue')['default']
    Error: typeof import('./components/Error.vue')['default']
    Login: typeof import('./components/login.vue')['default']
    MyCard: typeof import('./components/myCard.vue')['default']
    MyChart: typeof import('./components/myChart.vue')['default']
    MyChat: typeof import('./components/myChat.vue')['default']
    MyEarth: typeof import('./components/myEarth.vue')['default']
    MyForm: typeof import('./components/myForm.vue')['default']
    Myhome: typeof import('./components/myhome.vue')['default']
    MyNav: typeof import('./components/myNav.vue')['default']
    MySheet: typeof import('./components/mySheet.vue')['default']
    MyTest: typeof import('./components/myTest.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterTest: typeof import('./components/routerTest.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    SheetWebsocket: typeof import('./components/SheetWebsocket.vue')['default']
    SupMap: typeof import('./components/supMap.vue')['default']
    Test: typeof import('./components/test.vue')['default']
    UseCard: typeof import('./components/useCard.vue')['default']
  }
}
